export enum Country {
  AFGHANISTAN = 'AF',
  ALBANIA = 'AL',
  ALGERIA = 'DZ',
  ANDORRA = 'AD',
  ANGOLA = 'AO',
  ANTIGUA_AND_BARBUDA = 'AG',
  ARGENTINA = 'AR',
  ARMENIA = 'AM',
  AUSTRALIA = 'AU',
  AUSTRIA = 'AT',
  AZERBAIJAN = 'AZ',
  BAHAMAS = 'BS',
  BAHRAIN = 'BH',
  BANGLADESH = 'BD',
  BARBADOS = 'BB',
  BELARUS = 'BY',
  BELGIUM = 'BE',
  BELIZE = 'BZ',
  BENIN = 'BJ',
  BHUTAN = 'BT',
  BOLIVIA = 'BO',
  BOSNIA_AND_HERZEGOVINA = 'BA',
  BOTSWANA = 'BW',
  BRAZIL = 'BR',
  BRUNEI = 'BN',
  BULGARIA = 'BG',
  BURKINA_FASO = 'BF',
  BURUNDI = 'BI',
  CAMBODIA = 'KH',
  CAMEROON = 'CM',
  CANADA = 'CA',
  CAPE_VERDE = 'CV',
  CENTRAL_AFRICAN_REPUBLIC = 'CF',
  CHAD = 'TD',
  CHILE = 'CL',
  CHINA = 'CN',
  COLOMBIA = 'CO',
  COMOROS = 'KM',
  CONGO = 'CG',
  COSTA_RICA = 'CR',
  CROATIA = 'HR',
  CUBA = 'CU',
  CYPRUS = 'CY',
  CZECH_REPUBLIC = 'CZ',
  DENMARK = 'DK',
  DJIBOUTI = 'DJ',
  DOMINICA = 'DM',
  DOMINICAN_REPUBLIC = 'DO',
  ECUADOR = 'EC',
  EGYPT = 'EG',
  EL_SALVADOR = 'SV',
  EQUATORIAL_GUINEA = 'GQ',
  ERITREA = 'ER',
  ESTONIA = 'EE',
  ESWATINI = 'SZ',
  ETHIOPIA = 'ET',
  FIJI = 'FJ',
  FINLAND = 'FI',
  FRANCE = 'FR',
  GABON = 'GA',
  GAMBIA = 'GM',
  GEORGIA = 'GE',
  GERMANY = 'DE',
  GHANA = 'GH',
  GREECE = 'GR',
  GRENADA = 'GD',
  GUATEMALA = 'GT',
  GUINEA = 'GN',
  GUINEA_BISSAU = 'GW',
  GUYANA = 'GY',
  // HAITI = 'HT',
  // HONDURAS = 'HN',
  // HUNGARY = 'HU',
  // ICELAND = 'IS',
  // INDIA = 'IN',
  // INDONESIA = 'ID',
  // IRAN = 'IR',
  // IRAQ = 'IQ',
  // IRELAND = 'IE',
  // ISRAEL = 'IL',
  // ITALY = 'IT',
  // JAMAICA = 'JM',
  // JAPAN = 'JP',
  // JORDAN = 'JO',
  // KAZAKHSTAN = 'KZ',
  // KENYA = 'KE',
  // KIRIBATI = 'KI',
  // KOREA_NORTH = 'KP',
  // KOREA_SOUTH = 'KR',
  // KUWAIT = 'KW',
  // KYRGYZSTAN = 'KG',
  // LAOS = 'LA',
  // LATVIA = 'LV',
  // LEBANON = 'LB',
  // LESOTHO = 'LS',
  // LIBERIA = 'LR',
  // LIBYA = 'LY',
  // LIECHTENSTEIN = 'LI',
  // LITHUANIA = 'LT',
  // LUXEMBOURG = 'LU',
  // MADAGASCAR = 'MG',
  // MALAWI = 'MW',
  // MALAYSIA = 'MY',
  // MALDIVES = 'MV',
  // MALI = 'ML',
  // MALTA = 'MT',
  // MARSHALL_ISLANDS = 'MH',
  // MAURITANIA = 'MR',
  // MAURITIUS = 'MU',
  // MEXICO = 'MX',
  // MICRONESIA = 'FM',
  // MOLDOVA = 'MD',
  // MONACO = 'MC',
  // MONGOLIA = 'MN',
  // MONTENEGRO = 'ME',
  // MOROCCO = 'MA',
  // MOZAMBIQUE = 'MZ',
  // MYANMAR = 'MM',
  // NAMIBIA = 'NA',
  // NAURU = 'NR',
  // NEPAL = 'NP',
  // NETHERLANDS = 'NL',
  // NEW_ZEALAND = 'NZ',
  // NICARAGUA = 'NI',
  // NIGER = 'NE',
  // NIGERIA = 'NG',
  // NORTH_MACEDONIA = 'MK',
  // NORWAY = 'NO',
  // OMAN = 'OM',
  // PAKISTAN = 'PK',
  // PALAU = 'PW',
  // PALESTINE = 'PS',
  // PANAMA = 'PA',
  // PAPUA_NEW_GUINEA = 'PG',
  // PARAGUAY = 'PY',
  // PERU = 'PE',
  // PHILIPPINES = 'PH',
  // POLAND = 'PL',
  // PORTUGAL = 'PT',
  // QATAR = 'QA',
  // ROMANIA = 'RO',
  // RUSSIA = 'RU',
  // RWANDA = 'RW',
  // SAINT_KITTS_AND_NEVIS = 'KN',
  // SAINT_LUCIA = 'LC',
  // SAINT_VINCENT_AND_THE_GRENADINES = 'VC',
  // SAMOA = 'WS',
  // SAN_MARINO = 'SM',
  // SAO_TOME_AND_PRINCIPE = 'ST',
  // SAUDI_ARABIA = 'SA',
  // SENEGAL = 'SN',
  // SERBIA = 'RS',
  // SEYCHELLES = 'SC',
  // SIERRA_LEONE = 'SL',
  // SINGAPORE = 'SG',
  // SLOVAKIA = 'SK',
  // SLOVENIA = 'SI',
  // SOLOMON_ISLANDS = 'SB',
  // SOMALIA = 'SO',
  // SOUTH_AFRICA = 'ZA',
  // SOUTH_SUDAN = 'SS',
  // SPAIN = 'ES',
  // SRI_LANKA = 'LK',
  // SUDAN = 'SD',
  // SURINAME = 'SR',
  // SWEDEN = 'SE',
  // SWITZERLAND = 'CH',
  // SYRIA = 'SY',
  // TAIWAN = 'TW',
  // TAJIKISTAN = 'TJ',
  // TANZANIA = 'TZ',
  // THAILAND = 'TH',
  // TIMOR_LESTE = 'TL',
  // TOGO = 'TG',
  // TONGA = 'TO',
  // TRINIDAD_AND_TOBAGO = 'TT',
  // TUNISIA = 'TN',
  // TURKEY = 'TR',
  // TURKMENISTAN = 'TM',
  // TUVALU = 'TV',
  // UGANDA = 'UG',
  // UKRAINE = 'UA',
  // UNITED_ARAB_EMIRATES = 'AE',
  // UNITED_KINGDOM = 'GB',
  // UNITED_STATES = 'US',
  // URUGUAY = 'UY',
  // UZBEKISTAN = 'UZ',
  // VANUATU = 'VU',
  // VATICAN_CITY = 'VA',
  // VENEZUELA = 'VE',
  // VIETNAM = 'VN',
  // YEMEN = 'YE',
  // ZAMBIA = 'ZM',
  // ZIMBABWE = 'ZW',
}
export const CountryDetails: Record<Country, { name: string; flag: string }> = {
  [Country.AFGHANISTAN]: {
    name: 'Afghanistan',
    flag: 'https://example.com/flags/af.png',
  },
  [Country.ALBANIA]: {
    name: 'Albania',
    flag: 'https://example.com/flags/al.png',
  },
  [Country.ALGERIA]: {
    name: 'Algeria',
    flag: 'https://example.com/flags/dz.png',
  },
  [Country.ANDORRA]: {
    name: 'Andorra',
    flag: 'https://example.com/flags/ad.png',
  },
  [Country.ANGOLA]: {
    name: 'Angola',
    flag: 'https://example.com/flags/ao.png',
  },
  [Country.ANTIGUA_AND_BARBUDA]: {
    name: 'Antigua and Barbuda',
    flag: 'https://example.com/flags/ag.png',
  },
  [Country.ARGENTINA]: {
    name: 'Argentina',
    flag: 'https://example.com/flags/ar.png',
  },
  [Country.ARMENIA]: {
    name: 'Armenia',
    flag: 'https://example.com/flags/am.png',
  },
  [Country.AUSTRALIA]: {
    name: 'Australia',
    flag: 'https://example.com/flags/au.png',
  },
  [Country.AUSTRIA]: {
    name: 'Austria',
    flag: 'https://example.com/flags/at.png',
  },
  [Country.AZERBAIJAN]: {
    name: 'Azerbaijan',
    flag: 'https://example.com/flags/az.png',
  },
  [Country.BAHAMAS]: {
    name: 'Bahamas',
    flag: 'https://example.com/flags/bs.png',
  },
  [Country.BAHRAIN]: {
    name: 'Bahrain',
    flag: 'https://example.com/flags/bh.png',
  },
  [Country.BANGLADESH]: {
    name: 'Bangladesh',
    flag: 'https://example.com/flags/bd.png',
  },
  [Country.BARBADOS]: {
    name: 'Barbados',
    flag: 'https://example.com/flags/bb.png',
  },
  [Country.BELARUS]: {
    name: 'Belarus',
    flag: 'https://example.com/flags/by.png',
  },
  [Country.BELGIUM]: {
    name: 'Belgium',
    flag: 'https://example.com/flags/be.png',
  },
  [Country.BELIZE]: {
    name: 'Belize',
    flag: 'https://example.com/flags/bz.png',
  },
  [Country.BENIN]: {
    name: 'Benin',
    flag: 'https://example.com/flags/bj.png',
  },
  [Country.BHUTAN]: {
    name: 'Bhutan',
    flag: 'https://example.com/flags/bt.png',
  },
  [Country.BOLIVIA]: {
    name: 'Bolivia',
    flag: 'https://example.com/flags/bo.png',
  },
  [Country.BOSNIA_AND_HERZEGOVINA]: {
    name: 'Bosnia and Herzegovina',
    flag: 'https://example.com/flags/ba.png',
  },
  [Country.BOTSWANA]: {
    name: 'Botswana',
    flag: 'https://example.com/flags/bw.png',
  },
  [Country.BRAZIL]: {
    name: 'Brazil',
    flag: 'https://example.com/flags/br.png',
  },
  [Country.BRUNEI]: {
    name: 'Brunei',
    flag: 'https://example.com/flags/bn.png',
  },
  [Country.BULGARIA]: {
    name: 'Bulgaria',
    flag: 'https://example.com/flags/bg.png',
  },
  [Country.BURKINA_FASO]: {
    name: 'Burkina Faso',
    flag: 'https://example.com/flags/bf.png',
  },
  [Country.BURUNDI]: {
    name: 'Burundi',
    flag: 'https://example.com/flags/bi.png',
  },
  [Country.CAMBODIA]: {
    name: 'Cambodia',
    flag: 'https://example.com/flags/kh.png',
  },
  [Country.CAMEROON]: {
    name: 'Cameroon',
    flag: 'https://example.com/flags/cm.png',
  },
  [Country.CANADA]: {
    name: 'Canada',
    flag: 'https://example.com/flags/ca.png',
  },
  [Country.CAPE_VERDE]: {
    name: 'Cape Verde',
    flag: 'https://example.com/flags/cv.png',
  },
  [Country.CENTRAL_AFRICAN_REPUBLIC]: {
    name: 'Central African Republic',
    flag: 'https://example.com/flags/cf.png',
  },
  [Country.CHAD]: {
    name: 'Chad',
    flag: 'https://example.com/flags/td.png',
  },
  [Country.CHILE]: {
    name: 'Chile',
    flag: 'https://example.com/flags/cl.png',
  },
  [Country.CHINA]: {
    name: 'China',
    flag: 'https://example.com/flags/cn.png',
  },
  [Country.COLOMBIA]: {
    name: 'Colombia',
    flag: 'https://example.com/flags/co.png',
  },
  [Country.COMOROS]: {
    name: 'Comoros',
    flag: 'https://example.com/flags/km.png',
  },
  [Country.CONGO]: {
    name: 'Congo',
    flag: 'https://example.com/flags/cg.png',
  },
  [Country.COSTA_RICA]: {
    name: 'Costa Rica',
    flag: 'https://example.com/flags/cr.png',
  },
  [Country.CROATIA]: {
    name: 'Croatia',
    flag: 'https://example.com/flags/hr.png',
  },
  [Country.CUBA]: {
    name: 'Cuba',
    flag: 'https://example.com/flags/cu.png',
  },
  [Country.CYPRUS]: {
    name: 'Cyprus',
    flag: 'https://example.com/flags/cy.png',
  },
  [Country.CZECH_REPUBLIC]: {
    name: 'Czech Republic',
    flag: 'https://example.com/flags/cz.png',
  },
  [Country.DENMARK]: {
    name: 'Denmark',
    flag: 'https://example.com/flags/dk.png',
  },
  [Country.DJIBOUTI]: {
    name: 'Djibouti',
    flag: 'https://example.com/flags/dj.png',
  },
  [Country.DOMINICA]: {
    name: 'Dominica',
    flag: 'https://example.com/flags/dm.png',
  },
  [Country.DOMINICAN_REPUBLIC]: {
    name: 'Dominican Republic',
    flag: 'https://example.com/flags/do.png',
  },
  [Country.ECUADOR]: {
    name: 'Ecuador',
    flag: 'https://example.com/flags/ec.png',
  },
  [Country.EGYPT]: {
    name: 'Egypt',
    flag: 'https://example.com/flags/eg.png',
  },
  [Country.EL_SALVADOR]: {
    name: 'El Salvador',
    flag: 'https://example.com/flags/sv.png',
  },
  [Country.EQUATORIAL_GUINEA]: {
    name: 'Equatorial Guinea',
    flag: 'https://example.com/flags/gq.png',
  },
  [Country.ERITREA]: {
    name: 'Eritrea',
    flag: 'https://example.com/flags/er.png',
  },
  [Country.ESTONIA]: {
    name: 'Estonia',
    flag: 'https://example.com/flags/ee.png',
  },
  [Country.ESWATINI]: {
    name: 'Eswatini',
    flag: 'https://example.com/flags/sz.png',
  },
  [Country.ETHIOPIA]: {
    name: 'Ethiopia',
    flag: 'https://example.com/flags/et.png',
  },
  [Country.FIJI]: {
    name: 'Fiji',
    flag: 'https://example.com/flags/fj.png',
  },
  [Country.FINLAND]: {
    name: 'Finland',
    flag: 'https://example.com/flags/fi.png',
  },
  [Country.FRANCE]: {
    name: 'France',
    flag: 'https://example.com/flags/fr.png',
  },
  [Country.GABON]: {
    name: 'Gabon',
    flag: 'https://example.com/flags/ga.png',
  },
  [Country.GAMBIA]: {
    name: 'Gambia',
    flag: 'https://example.com/flags/gm.png',
  },
  [Country.GEORGIA]: {
    name: 'Georgia',
    flag: 'https://example.com/flags/ge.png',
  },
  [Country.GERMANY]: {
    name: 'Germany',
    flag: 'https://example.com/flags/de.png',
  },
  [Country.GHANA]: {
    name: 'Ghana',
    flag: 'https://example.com/flags/gh.png',
  },
  [Country.GREECE]: {
    name: 'Greece',
    flag: 'https://example.com/flags/gr.png',
  },
  [Country.GRENADA]: {
    name: 'Grenada',
    flag: 'https://example.com/flags/gd.png',
  },
  [Country.GUATEMALA]: {
    name: 'Guatemala',
    flag: 'https://example.com/flags/gt.png',
  },
  [Country.GUINEA]: {
    name: 'Guinea',
    flag: 'https://example.com/flags/gn.png',
  },
  [Country.GUINEA_BISSAU]: {
    name: 'Guinea-Bissau',
    flag: 'https://example.com/flags/gw.png',
  },
  [Country.GUYANA]: {
    name: 'Guyana',
    flag: 'https://example.com/flags/gy.png',
  },
};
